apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-ddns-controller-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-ddns-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "go-ddns-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
