---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-ddns-cluster-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers/finalizers
  verbs:
  - update
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
