apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "go-ddns-controller.serviceAccountName" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-ddns-cluster-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "go-ddns-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
