---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers/finalizers
  verbs:
  - update
- apiGroups:
  - ddns.stefangenov.site
  resources:
  - notifiers/status
  verbs:
  - get
  - patch
  - update
