apiVersion: ddns.stefangenov.site/v1alpha1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: go-ddns-controller
    app.kubernetes.io/managed-by: kustomize
  name: ingress-sample
spec:
  # TODO(user): Add fields here
