## Append samples of your project ##
resources:
- ddns_v1alpha1_provider.yaml
- ddns_v1alpha1_notifier.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
- cloudflareSecret.yaml
- configMaps.yaml
